#!/bin/bash

DATE=`date`
echo "BD Trigger Script Called - $DATE" >> /var/log/rip.log

TITLE=`udevadm info -q env -n /dev/sr0 | grep ID_FS_LABEL | cut -d'=' -f2 | head -n 1`
mkdir -p /media/storage/bluray/$TITLE
echo "Saving $TITLE to /media/storage/bluray/$TITLE" >> /var/log/rip.log
/usr/bin/makemkvcon --directio=true --cache=1024 --upnp=false --minlength=900 -r mkv disc:0 all /media/storage/bluray/$TITLE >> /var/log/rip.log
echo "Syncronising /media/storage/bluray to /media/bluray/Encoded" >> /var/log/rig.log
rsync -avz /media/storage/bluray /media/bluray/Encoded > /var/log/rip.log
if [ $? -eq 0 ]; then
  rm -rf /media/storage/bluray/$TITLE
  echo "$TITLE completed successfully" >> /var/log/rip.log
  eject /dev/sr0
else
  echo "Rsync error for $TITLE" >> /var/log/rip.log
fi


