#!/bin/bash

DATE=`date`
echo "DVD Trigger Script Called - $DATE" >> /var/log/rip.log
echo "Parameters: $1" >> /var/log/rip.log

TITLE=`udevadm info -q env -n /dev/$1 | grep ID_FS_LABEL | cut -d'=' -f2 | head -n 1`
mkdir -p /media/storage/dvd/$TITLE
echo "Saving $TITLE to /media/storage/dvd/$TITLE" >> /var/log/rip.log
/usr/bin/makemkvcon --directio=true --cache=1024 --upnp=false --minlength=900 -r mkv disc:0 all /media/storage/dvd/$TITLE >> /var/log/rip.log
echo "Syncronising /media/storage/dvd to /media/dvd/Encoded" >> /var/log/rip.log
rsync -avz /media/storage/dvd /media/dvd/Encoded >> /var/log/rip.log
if [ $? -eq 0 ]; then
  rm -rf /media/storage/dvd/*
  echo "$TITLE completed successfully" >> /var/log/rip.log
  eject /dev/sr0
else
  echo "Rsync error for $TITLE" >> /var/log/rip.log
fi


